### ISSUE TITLE
Dropbox have depricated V1

### ISSUE THREAD

**Issue by sudeeptalati** [demisang/yii2-dropbox-backup#1]
Hello

I really liked your extension for backup and I was trying to implement the dropbox version.

Unfortunately the dropbox have stopped supporting v1 and have moved to V2.

Will you be updating your version.

Thanks

**Comment by demisang** [comment]
Thanks for response, now I see what I can do

**Comment by ukccatc** [comment]
Hi
Do you plan to update it to v2? If some help needed, advice.

**Comment by sudeeptalati** [comment]
I did little changes to make it work 
[BackupController.php.txt](https://github.com/demisang/yii2-dropbox-backup/files/2061802/BackupController.php.txt)

**Comment by earx** [comment]
To support V2 API - I've created my own fork of this component, @demisang please, feel free to use my code to update your component

Here it is:
https://github.com/earx/yii2-dropbox-backup

**Comment by vlaim** [comment]
@earx Thanks, that's a great solution

**Comment by demisang** [comment]
Migrated to Dropbox API v2, please change composer.json:  `"demi/dropbox-backup": "~2.0"` or `composer update "demi/dropbox-backup"`

Fully compatible with the first version. No additional actions.
